name: Build and deploy Astro site

on:
  workflow_call:
    outputs:
      BASE_URL:
        description: "The Github Pages URL for the repository"
        value: ${{ jobs.deploy.outputs.BASE_URL }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.1
       if: always()
     - name: Install packages
       run: |
        npm install
        npx astro build
     - name: Setup Github Pages
       uses: actions/configure-pages@v5.0.0
       if: always()
     - name: Upload artifact archive
       uses: actions/upload-pages-artifact@v4.0.0
       with:
        path: ./dist
       if: always()
  deploy:
    outputs:
      BASE_URL: ${{ steps.deployment.outputs.page_url }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5